apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworldspringboot.fullname" . }}
  labels:
    {{- include "helloworldspringboot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.portName }}      
  selector:
    {{- include "helloworldspringboot.selectorLabels" . | nindent 4 }}
